version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"  # Le port 5432 de PostgreSQL est exposé sur le port 5432 de votre machine
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistance des données
    networks:
      - springboot-network

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "5433:5433"
      depends_on:
        - postgres

networks:
  springboot-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
