version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"  # Le port 5432 de PostgreSQL est exposé sur le port 5432 de votre machine
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistance des données
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
